import React, { useEffect } from "react";
import "../styles/TermsAndConditions.css";

const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <main className="tc-wrapper">
      <div className="tc-content-box">
        <img
          className="tc-banner-img"
          src="https://www.devalayas.in/assets/images/tc.png"
          alt="Terms Banner"
        />
        <h5 className="tc-heading">Terms and Conditions :</h5>
        <p className="tc-paragraph">
          This document is an electronic record in terms of the Indian Contract Act, 1872, Information Technology Act, 2000, the rules made there under, and the amended provisions pertaining to electronic records in various other statutes, as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system it does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires publishing the rules and regulations, privacy policy and Terms of Service for the access or usage of https://devalayas.com (“Website”) and DEVALAYA (“App”). The Website and App are owned and operated by Anek Technologies Private Limited with its place of business at SP OFFICE ROAD, NEAR KOLHAPUR CIRCLE, BELGAUM, KARNATAKA 590010, INDIA. Please read these Terms of Service fully and carefully before using the Website or App and the services, features, content or applications maintained by Anek Technologies Private Limited (“devalaya” “we”, “us” or “our”).
        </p>

        <p className="tc-paragraph">
          <strong>IF YOU DO NOT AGREE TO BE BOUND BY ALL CONDITIONS/CLAUSES CAPTURED HERE UNDER, PLEASE DO NOT USE THE WEBSITE OR APP.</strong>
        </p>

        <h5 className="tc-heading">1. Definition:</h5>
        <p className="tc-paragraph">
          1.1 “Content” shall include, without limitation, information, data, text, photographs, videos, shoots, audio clips, written posts and comments, software, scripts, graphics, and interactive features generated, provided, or otherwise made accessible on or through the Website and App. Such Content shall either be owned by Devalaya or owned by various temple or guru partners along with rights granted to Devalaya to publish such content on the Website and App and; made available to the users through Website/App.
        </p>
        <p className="tc-paragraph">
          1.2 “Services” shall mean the Content (defined hereunder), the video streaming of the Content, Website/App, and any other features, functionalities, applications, materials, prasad service, puja service, donation service or other Services (defined hereunder) offered from time to time on the App or Website in connection with any of the above, however accessed, are referred to collectively as the “Services” or the “App Services”)
        </p>

        <h5 className="tc-heading">2. Acceptance of Terms and Conditions:</h5>
        <p className="tc-paragraph">By registering for and/or using the Services in any manner, you agree to all of the terms and conditions contained herein ("Terms").</p>

        <h5 className="tc-heading">Eligibility:</h5>
        <p className="tc-paragraph">You represent and warrant that You are at least 18 years of age...</p>

        <h5 className="tc-heading">Registration:</h5>
        <p className="tc-paragraph">To sign up for the Services, You must register for an account...</p>

        <h5 className="tc-heading">3. The use of the Website/App is subject to the following conditions:</h5>
        <ol className="tc-list">
          <li>The Content hosted on the Website/App is for personal viewing purposes...</li>
          <li>The booking of forthcoming Puja...</li>
          <li>After performance of the puja, the video will be made available...</li>
        </ol>

        <h5 className="tc-heading">4. Copyright notice:</h5>
        <p className="tc-paragraph">The contents of the Website and App...</p>

        <h5 className="tc-heading">5. Third Party Services:</h5>
        <p className="tc-paragraph">The Services may permit You to link to other websites...</p>

        <h5 className="tc-heading">6. Payment Method and Refund policy:</h5>
        <p className="tc-paragraph">The terms of Your payment will be based on Your Payment Method...</p>

        <h5 className="tc-heading">7. Rules and Conduct:</h5>
        <p className="tc-paragraph">As a condition of use, You promise not to use the Service for any purpose that is prohibited...</p>

        <h5 className="tc-heading">8. Typographical Errors:</h5>
        <p className="tc-paragraph">In the event that an entry listed on the Services is mistakenly listed at an incorrect price...</p>

        <h5 className="tc-heading">9. Termination:</h5>
        <p className="tc-paragraph">We may terminate Your access to all or any part of the Services at any time...</p>

        <h5 className="tc-heading">10. Warranty Disclaimer:</h5>
        <p className="tc-paragraph">The Services and Content are provided “as is”, “as available” and without warranty of any kind...</p>

        <h5 className="tc-heading">11. Indemnification:</h5>
        <p className="tc-paragraph">You shall defend, indemnify, and hold us harmless...</p>

        <h5 className="tc-heading">12. Limitation of Liability:</h5>
        <p className="tc-paragraph">In no event shall we, nor our directors, employees, agents, partners or content providers...</p>

        <h5 className="tc-heading">13. Governing Law and Jurisdiction:</h5>
        <p className="tc-paragraph">These Terms of Service shall be governed by and construed in accordance with the laws of India...</p>

        <h5 className="tc-heading">14. Modification:</h5>
        <p className="tc-paragraph">We reserve the right, in our sole discretion, to modify or replace any of these Terms...</p>

        <h5 className="tc-heading">15. Entire Agreement and Severability:</h5>
        <p className="tc-paragraph">These Terms of Service and Privacy Policy constitute entire agreement between You and us...</p>

        <h5 className="tc-heading">16. Force Majeure:</h5>
        <p className="tc-paragraph">We shall not be liable for any failure to perform our obligations hereunder...</p>

        <h5 className="tc-heading">17. Assignment:</h5>
        <p className="tc-paragraph">These Terms of Service are personal to You...</p>

        <h5 className="tc-heading">18. Agency:</h5>
        <p className="tc-paragraph">No agency, partnership, joint venture, or employment relationship is created as a result...</p>

        <h5 className="tc-heading">19. No Waiver:</h5>
        <p className="tc-paragraph">Our failure to enforce any part of these Terms of Service shall not constitute a waiver...</p>

        <h5 className="tc-heading">20. Support:</h5>
        <p className="tc-paragraph">If You have any questions regarding the Service, please contact us at info@devalayas.com or call 8951269111.</p>

        <h5 className="tc-heading">21. Headings:</h5>
        <p className="tc-paragraph">The section and paragraph headings in these Terms of Service are for convenience only...</p>

        <h5 className="tc-heading">22. Privacy Policy:</h5>
        <p className="tc-paragraph">The Privacy Policy is separately available on the Website...</p>

        <h5 className="tc-heading">23. Prasadam:</h5>
        <p className="tc-paragraph">Quality and Quantity of the PRASADA is wholly and solely the responsibility of the pujari and the temple...</p>

        <p className="tc-paragraph">Thank you!</p>
        <p className="tc-paragraph">Email: info@devalayas.com</p>
      </div>
    </main>
  );
};

export default TermsAndConditions;
